name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: curl, mbstring
          coverage: none

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Run tests
        run: vendor/bin/phpunit --colors=always

      - name: Build release artifact
        run: |
          chmod +x scripts/build-release.sh
          ./scripts/build-release.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: the-news-log
          path: dist/the-news-log.zip
